### ISSUE TITLE
hey, are you guys doing the hack club MANOR next year? becuase i could do it next year

### ISSUE THREAD

**Issue by webbrowser11** [NeonGamerBot-QK/spooky-boba#2]
i just wanted to know!

**Comment by NeonGamerBot-QK** [comment]
I don’t run the event I recommend going to the hackclub slack to get more info on this !

**Comment by webbrowser11** [comment]
i dont have a slack account though i have to wait 1 more year. to get into middle school...

**Comment by NeonGamerBot-QK** [comment]
> i dont have a slack account though i have to wait 1 more year. to get into middle school...

@webbrowser11 
"Depends, next year we may have a new event." - (person who is holding the event)

**Comment by webbrowser11** [comment]
ok
